services:
  catalog-db:
    container_name: catalog-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/
  
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS="https://+;http://+"
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=catalog-db;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - catalog-db
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
#      - ${HOME}/.aspnet/https:/https/ mcr.microsoft.com/dotnet/samples:aspnetapp
#      - ~/.aspnet/https:/root/.aspnet/https:aspnetapp.pfx
#      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
#      - ${APPDATA}/Microsoft/UserSecrets:/private/home/app/.microsoft/usersecrets:ro
#      - ${APPDATA}/ASP.NET/Https:/private/home/app/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
#      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:aspnetapp
      - ${APPDATA}/.aspnet/https:/https:ro